# Generated by Django 4.0.3 on 2022-03-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=250, null=True)),
                ('msg', models.CharField(blank=True, max_length=250, null=True)),
                ('lead_origin', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
